---
linters:
  # Disable all linters.
  # Default: false
  disable-all: true

  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
